### ISSUE TITLE
Unable to connect to postgres

### ISSUE THREAD

**Issue by ishantanu** [guymorita/Mosaic-Films---Recommendation-Engine-Demo#26]
Hi, I am unable to connect to postgres on Ubuntu with command postgres -D /path/to/postgres-installation. While trying to import movie recs, I get error from sequelize package:
role 'username' does not exists.

But when I tried viewing users using psql, the user was there. 

This worked fine with macos. Is there anything else which should be done for Ubuntu?

**Comment by guymorita** [comment]
Hey @iamShantanu101, haven't tried and don't intend to try to get it running on Ubuntu. You're welcome to submit a change if you can figure it out.

**Comment by ishantanu** [comment]
@guymorita Okay. Can you tell me what this line exactly does:
`postgres -D /usr/local/var/postgres`
